mutation createCompany($name: String, $description: String, $image: String, $isParentCompany: Boolean, $addressId: Int) {
    createCompany(name: $name, description: $description, image: $image, isParentCompany: $isParentCompany, addressId: $addressId) {
        id
		name
		description
		image
		isParentCompany
		addressId
		latitude
		longitude
		industryId
		gst
		angellist 
		discord
		facebook
		github
		google
		instagram
		justdial
		linkedin
		pinterest
		slack
		tiktok
		twitter
		web
		youtube
		isActive
		isHidden
		created
		updated
    }
}