query states($id: Int, $countryId: Int, $isHidden: Boolean) {
    states(id: $id, countryId: $countryId, isHidden: $isHidden) {
		id
        name
		countryId 
		loccode
		status
		isHidden
		created
		updated
	}
}