export const tableChartData = [{
  Vertical: 'BCM',
  companyData: [{
    Company: 'CA-CIB',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 1,
    ReasonsOfRatingDifference: 'Attrition,Backlog,Quality,Resourcing',
  },
  {
    Company: 'Capital One',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Morgan Stanley',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Quality',
  },
  {
    Company: 'Ing Banking',
    AccountType: 'Accelerator',
    VoiceOfSales: 2,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Nucleus Financial',
    AccountType: 'Accelerator',
    VoiceOfSales: 1,
    VoiceOfDelivery: 4,
    ReasonsOfRatingDifference: 'SLAs',
  },
  {
    Company: 'TD Bank Group',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'TIAA',
    AccountType: 'Accelerator',
    VoiceOfSales: 5,
    VoiceOfDelivery: 1,
    ReasonsOfRatingDifference: 'Client expectation',
  },
  ],
},
{
  Vertical: 'CGRLH',
  companyData: [{
    Company: 'CA-CIB',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 1,
    ReasonsOfRatingDifference: 'Attrition,Backlog,Quality,Resourcing',
  },
  {
    Company: 'Capital One',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Morgan Stanley',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Quality',
  },
  {
    Company: 'Ing Banking',
    AccountType: 'Accelerator',
    VoiceOfSales: 2,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  }, {
    Company: 'Ing Banking',
    AccountType: 'Accelerator',
    VoiceOfSales: 2,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Nucleus Financial',
    AccountType: 'Accelerator',
    VoiceOfSales: 1,
    VoiceOfDelivery: 4,
    ReasonsOfRatingDifference: 'SLAs',
  },
  {
    Company: 'TD Bank Group',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  ],
},
{
  Vertical: 'HMS',
  companyData: [{
    Company: 'CA-CIB',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 1,
    ReasonsOfRatingDifference: 'Attrition,Backlog,Quality,Resourcing',
  },
  {
    Company: 'Capital One',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Morgan Stanley',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Quality',
  },
  {
    Company: 'Ing Banking',
    AccountType: 'Accelerator',
    VoiceOfSales: 2,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Morgan Stanley',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Quality',
  },
  {
    Company: 'Ing Banking',
    AccountType: 'Accelerator',
    VoiceOfSales: 2,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  }, {
    Company: 'Ing Banking',
    AccountType: 'Accelerator',
    VoiceOfSales: 2,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Nucleus Financial',
    AccountType: 'Accelerator',
    VoiceOfSales: 1,
    VoiceOfDelivery: 4,
    ReasonsOfRatingDifference: 'SLAs',
  },
  ],
},
{
  Vertical: 'Insurance',
  companyData: [{
    Company: 'CA-CIB',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 1,
    ReasonsOfRatingDifference: 'Attrition,Backlog,Quality,Resourcing',
  },
  {
    Company: 'Capital One',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Capital One',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Morgan Stanley',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Quality',
  },
  {
    Company: 'Ing Banking',
    AccountType: 'Accelerator',
    VoiceOfSales: 2,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  {
    Company: 'Morgan Stanley',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Quality',
  },
  {
    Company: 'Morgan Stanley',
    AccountType: 'Champion',
    VoiceOfSales: 3,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Quality',
  },
  {
    Company: 'Ing Banking',
    AccountType: 'Accelerator',
    VoiceOfSales: 2,
    VoiceOfDelivery: 5,
    ReasonsOfRatingDifference: 'Resourcing',
  },
  ],
},
];
export default tableChartData;
