query {
    addresses {
        id
        name
        building
        landmark
        street
        pincode
        stateId
        userId
        isHidden
        created
        updated
    }
}