mutation createAddress($name: String!, $building: String!, $landmark: String!, $street: String!, $pincode: Int!, $stateId: Int!) {
  createAddress(name: $name, building: $building, landmark: $landmark, street: $street, pincode: $pincode, stateId: $stateId) {
    id
    name
    building
    landmark
    street
    pincode
    stateId
    userId
    isHidden
    created
    updated
  }
}