mutation updateAddress($name: String!, $building: String!, $landmark: String!, $street: String!, $pincode: Int!, $stateId: Int!, $userId: Int!, $isHidden: Boolean) {
  updateAddress(name: $name, building: $building, landmark: $landmark, street: $street, pincode: $pincode, stateId: $stateId, userId: $userId, isHidden: $isHidden) {
    id
    name
    building
    landmark
    street
    pincode
    stateId
    userId
    isHidden
    created
    updated
  }
}