query getRootCauseVariations($fromDate: String!, $toDate: String!){
    getRootCauseVariations (fromDate: $fromDate, toDate: $toDate){
      verticalName
      companyName
      accountType
      voc
      vod
      keywordNames
    }
}