mutation UpdateUserCompany ($userCompanyId: Int!, $isDeleted: Int!, $companyVerticalId: Int!, $userId: Int!) {
  updateUserCompany(userCompanyId: $userCompanyId, isDeleted: $isDeleted, companyVerticalId: $companyVerticalId, userId: $userId) {
    id
    companyVerticalId
    userId
  }
}